### ISSUE TITLE
NoSuchMethodError when invoking views.html.language_selection

### ISSUE THREAD

**Issue by omair-ali** [hmrc/play-language#16]
Apologies, this may not be the place to ask technical questions but I am not sure where else to get help / solve issues using this lib.

I am getting the following error using play-language 3.4.0 and Play 2.6:

java.lang.NoSuchMethodError: views.html.language_selection_Scope0$language_selection_Scope1$language_selection._display_(Ljava/lang/Object;Lscala/reflect/Manifest;)Lplay/twirl/api/Appendable;
	at views.html.language_selection_Scope0$language_selection_Scope1$language_selection.apply(language_selection.template.scala:30)

I am trying to invoke the following from my header template:
@views.html.language_selection(appConfig.languageMap, appConfig.routeToSwitchLanguage, Some("govuk-header__navigation-item"))

Please advise what I may be doing wrong?

**Comment by danewatts** [comment]
Play-language does not currently support Play 2.6. Please implement the functionality yourself within your microservice.
